version: '3.8'

services:
  yolo8vn_raspberry:
    build:
      context: .
      dockerfile: Dockerfile
    image: yolo8vn_raspberry:latest
    container_name: yolo8vn_raspberry_container
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY}
    restart: unless-stopped