version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: yolo8vn_server:latest
    container_name: yolo8vn_server_container
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "65432:65432"
    networks:
      - yolo_network
    stop_signal: SIGINT

networks:
  yolo_network:
    driver: bridge