version: '3.8'
services:
  yolo8vn_raspberry:
    build:
      context: .
      dockerfile: Dockerfile.tracker
    image: yolo8vn_tracker:latest
    container_name: yolo8vn_tracker_container
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - server
    networks:
      - yolo_network
    stop_signal: SIGINT

networks:
  yolo_network:
    driver: bridge