services:
  camera:
    build:
      context: .
      dockerfile: Dockerfile
    image: camera_pi_image
    container_name: camera_pi_container
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./output_docker_app:/app/output
    devices:
      - /dev/video2:/dev/video2
    stop_signal: SIGINT
    stop_grace_period: 30s
    restart: unless-stopped
